<#
.SYNOPSIS
    QianLingo 项目生成器
.DESCRIPTION
    检查全局模板目录 (~\.qianlingo)，若无模板则创建默认占位符
#>

$ErrorActionPreference = "Stop"

# ==========================================
# 0. 全局模板检查与初始化
# ==========================================

$globalDir = Join-Path $env:USERPROFILE ".qianlingo"
$globalWebTemplate = Join-Path $globalDir "web.md"
$globalUiTemplate = Join-Path $globalDir "ui.md"

Write-Host ""
Write-Host "=======================================================" -ForegroundColor Cyan
Write-Host "              QianLingo Generator v1.0                 " -ForegroundColor Cyan
Write-Host "=======================================================" -ForegroundColor Cyan
Write-Host ""

# 检查并创建全局目录
if (-not (Test-Path $globalDir)) {
    Write-Host "[INIT] 创建全局模板目录: $globalDir" -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $globalDir -Force | Out-Null
}

# 创建默认 web.md 模板
if (-not (Test-Path $globalWebTemplate)) {
    Write-Host "[INIT] 创建默认模板: web.md" -ForegroundColor Yellow
    @'
# {{MODE}} - Backend Configuration

## Project Info
- **Date**: {{DATE}}
- **Timestamp**: {{TIMESTAMP}}
- **Spring Version**: {{SPRING_VERSION}}
- **Database**: {{DATABASE}}
- **Backend Path**: {{BACKEND_PATH}}

## API Structure
"""
TODO: Define your API endpoints here
Example:
GET /api/v1/users
POST /api/v1/auth/login
"""

## Entity Definitions
"""
TODO: Define your database entities
Example:
User (id, username, email, created_at)
Order (id, user_id, amount, status)
"""

## Generated Notes
This file was generated by QianLingo on {{DATE}}.
Mode: {{MODE}}
Stack: {{SPRING_VERSION}} + {{DATABASE}}
'@ | Out-File -FilePath $globalWebTemplate -Encoding UTF8
    Write-Host "       已创建占位模板" -ForegroundColor DarkGray
}

# 创建默认 ui.md 模板
if (-not (Test-Path $globalUiTemplate)) {
    Write-Host "[INIT] 创建默认模板: ui.md" -ForegroundColor Yellow
    @'
# {{MODE}} - Frontend Configuration

## Project Info
- **Date**: {{DATE}}
- **Timestamp**: {{TIMESTAMP}}
- **View Technology**: {{VIEW_TECH}}
- **Vue Version**: {{VUE_VERSION}}
- **Backend Integration**: {{BACKEND_PATH}}

## Component Structure
"""
TODO: Define your UI components here
Example:
src/
  components/
    UserForm.vue
    DataTable.vue
  views/
    Dashboard.vue
    Login.vue
"""

## Styling Guidelines
"""
TODO: Define your CSS/Tailwind/Material config
Primary Color: #3B82F6
Secondary Color: #10B981
"""

## Generated Notes
This file was generated by QianLingo on {{DATE}}.
Mode: {{MODE}}
Frontend: {{VIEW_TECH}} {{VUE_VERSION}}
'@ | Out-File -FilePath $globalUiTemplate -Encoding UTF8
    Write-Host "       已创建占位模板" -ForegroundColor DarkGray
}

if ((Test-Path $globalWebTemplate) -and (Test-Path $globalUiTemplate)) {
    Write-Host "[OK] 全局模板就绪: $globalDir" -ForegroundColor Green
    Write-Host ""
}

# ==========================================
# 1. 选择生成的目录名
# ==========================================

Write-Host "步骤 1：选择项目内目录名称" -ForegroundColor Yellow
Write-Host "-------------------------------------------------------" -ForegroundColor Blue
Write-Host ""
Write-Host "[1] .agent    (通用 AI 代理目录)" -ForegroundColor Green
Write-Host "[2] .elian    (Elian 经典结构)" -ForegroundColor White
Write-Host "[3] .ai       (简洁 AI 目录)" -ForegroundColor White
Write-Host "[4] .prompt   (提示词工程)" -ForegroundColor White
Write-Host "[5] .claude   (Claude 风格)" -ForegroundColor White
Write-Host "[6] 自定义    (输入你自己的)" -ForegroundColor Magenta
Write-Host ""

do {
    $dirChoice = Read-Host "请选择 (1-6)"
} while ($dirChoice -notin @("1","2","3","4","5","6"))

switch ($dirChoice) {
    "1" { $dirName = ".agent" }
    "2" { $dirName = ".elian" }
    "3" { $dirName = ".ai" }
    "4" { $dirName = ".prompt" }
    "5" { $dirName = ".claude" }
    "6" { 
        do {
            $customName = Read-Host "请输入目录名 (建议以.开头，如 .myai)"
            if ([string]::IsNullOrWhiteSpace($customName)) {
                Write-Host "名称不能为空" -ForegroundColor Red
            }
        } while ([string]::IsNullOrWhiteSpace($customName))
        $dirName = $customName
    }
}

# ==========================================
# 2. 选择界面风格
# ==========================================

Write-Host ""
Write-Host "步骤 2：选择界面风格" -ForegroundColor Yellow
Write-Host "-------------------------------------------------------" -ForegroundColor Blue
Write-Host ""
Write-Host "[1] 专业版    (Professional)" -ForegroundColor White
Write-Host "[2] 极客版    (Hacker)" -ForegroundColor Green
Write-Host "[3] 友好版    (Friendly)" -ForegroundColor Magenta
Write-Host "[4] 极简版    (Minimal)" -ForegroundColor Cyan
Write-Host ""

do {
    $styleChoice = Read-Host "请选择风格 (1-4)"
} while ($styleChoice -notin @("1","2","3","4"))

# ==========================================
# 3. 风格函数
# ==========================================

function Show-Step {
    param([string]$Style, [int]$Step, [string]$Title)
    switch ($Style) {
        "1" {
            Write-Host ""
            Write-Host "-------------------------------------------------------" -ForegroundColor DarkBlue
            Write-Host " 步骤 $Step`: $Title" -ForegroundColor DarkBlue
            Write-Host "-------------------------------------------------------" -ForegroundColor DarkBlue
        }
        "2" {
            Write-Host ""
            Write-Host "[STEP_$Step] $Title..." -ForegroundColor Green
        }
        "3" {
            Write-Host ""
            Write-Host "📝 第 $Step 步：$Title" -ForegroundColor Magenta
            Write-Host "----------------------------------------" -ForegroundColor Gray
        }
        "4" {
            Write-Host ""
            Write-Host "[$Step/5] $Title" -ForegroundColor Cyan
        }
    }
}

function Show-Option {
    param([string]$Style, [string]$Key, [string]$Text, [string]$Desc, [bool]$Rec = $false)
    $c = if ($Rec) { "Green" } else { "White" }
    switch ($Style) {
        "1" {
            Write-Host "[$Key] $Text" -ForegroundColor $c
            if ($Desc) { Write-Host "    $Desc" -ForegroundColor Gray }
        }
        "2" {
            Write-Host "[$Key] $Text" -ForegroundColor $c
            if ($Desc) { Write-Host "    > $Desc" -ForegroundColor DarkGray }
        }
        "3" {
            Write-Host "[$Key] $Text" -ForegroundColor $c
            if ($Desc) { Write-Host "    $Desc" -ForegroundColor Gray }
        }
        "4" {
            Write-Host "$Key. $Text" -ForegroundColor $c
        }
    }
}

function Show-Success {
    param([string]$Style, [string]$Msg)
    switch ($Style) {
        "1" { Write-Host "[成功] $Msg" -ForegroundColor Green }
        "2" { Write-Host "[OK] $Msg" -ForegroundColor Green }
        "3" { Write-Host "✅ $Msg" -ForegroundColor Green }
        "4" { Write-Host "[OK] $Msg" -ForegroundColor Green }
    }
}

# ==========================================
# 4. 交互配置
# ==========================================

$currentPath = (Get-Location).Path
$projectDir = Join-Path $currentPath $dirName

Write-Host ""
switch ($styleChoice) {
    "1" { 
        Write-Host "当前路径：$currentPath" -ForegroundColor Gray
        Write-Host "将生成目录：$dirName" -ForegroundColor Gray
    }
    "2" { 
        Write-Host "[PWD] $currentPath" -ForegroundColor Gray
        Write-Host "[TARGET] $dirName/" -ForegroundColor Gray
    }
    "3" { 
        Write-Host "当前位置：$currentPath" -ForegroundColor Gray
        Write-Host "即将创建：$dirName 目录" -ForegroundColor Gray
    }
    "4" { 
        Write-Host "$currentPath\$dirName" -ForegroundColor Gray
    }
}
Write-Host ""

# 步骤 1：操作模式
Show-Step -Style $styleChoice -Step 1 -Title $(if($styleChoice -eq "1"){"操作模式"}elseif($styleChoice -eq "2"){"Mode"}elseif($styleChoice -eq "3"){"你想做什么？"}else{"Mode"})
Show-Option -Style $styleChoice -Key "1" -Text $(if($styleChoice -eq "1"){"初始化项目"}elseif($styleChoice -eq "2"){"Init"}else{"初始化"}) -Desc "创建完整项目结构"
Show-Option -Style $styleChoice -Key "2" -Text $(if($styleChoice -eq "1"){"新建任务"}elseif($styleChoice -eq "2"){"Task"}else{"新任务"}) -Desc "添加功能模块"
$p = switch ($styleChoice) { "2" {">"} "4" {"Select:"} default {"选择 (1-2)"} }
do { $op = Read-Host $p } while ($op -notin @("1","2"))
$mode = if ($op -eq "1") { $(if($styleChoice -eq "2"){"Init"}elseif($styleChoice -eq "4"){"Init"}else{"初始化"}) } else { $(if($styleChoice -eq "2"){"Task"}elseif($styleChoice -eq "4"){"Task"}else{"新建任务"}) }

# 步骤 2：后端位置
Show-Step -Style $styleChoice -Step 2 -Title $(if($styleChoice -eq "1"){"后端位置"}elseif($styleChoice -eq "2"){"Backend"}elseif($styleChoice -eq "3"){"后端在哪？"}else{"Backend"})
Show-Option -Style $styleChoice -Key "1" -Text $(if($styleChoice -eq "1"){"当前目录"}elseif($styleChoice -eq "2"){"Root"}else{"根目录"}) 
Show-Option -Style $styleChoice -Key "2" -Text $(if($styleChoice -eq "1"){"子文件夹"}elseif($styleChoice -eq "2"){"Subfolder"}else{"子目录"}) -Desc "如 backend/"
$p = switch ($styleChoice) { "2" {">"} "4" {"Select:"} default {"选择 (1-2)"} }
do { $bp = Read-Host $p } while ($bp -notin @("1","2"))
$backendPath = if ($bp -eq "1") { "." } else { Read-Host $(if($styleChoice -eq "2"){"Path:"}else{"路径"}) }

# 步骤 3：架构
Show-Step -Style $styleChoice -Step 3 -Title $(if($styleChoice -eq "1"){"技术架构"}elseif($styleChoice -eq "2"){"Stack"}elseif($styleChoice -eq "3"){"技术栈？"}else{"Stack"})
Show-Option -Style $styleChoice -Key "1" -Text "Spring Boot 2.x"
Show-Option -Style $styleChoice -Key "2" -Text "Spring Boot 3.x" -Rec $true
$p = switch ($styleChoice) { "2" {">"} "4" {"Select:"} default {"选择 (1-2)"} }
do { $arch = Read-Host $p } while ($arch -notin @("1","2"))
$spring = if ($arch -eq "1") { "SpringBoot2" } else { "SpringBoot3" }

# 步骤 4：前端
Show-Step -Style $styleChoice -Step 4 -Title $(if($styleChoice -eq "1"){"前端方案"}elseif($styleChoice -eq "2"){"Frontend"}elseif($styleChoice -eq "3"){"前端方案？"}else{"Frontend"})
Show-Option -Style $styleChoice -Key "1" -Text "Vue.js" -Rec $true
Show-Option -Style $styleChoice -Key "2" -Text "Freemarker MVC"
$p = switch ($styleChoice) { "2" {">"} "4" {"Select:"} default {"选择 (1-2)"} }
do { $fe = Read-Host $p } while ($fe -notin @("1","2"))
$view = if ($fe -eq "1") { "Vue" } else { "FreemarkerMVC" }

# 步骤 5：数据库
Show-Step -Style $styleChoice -Step 5 -Title $(if($styleChoice -eq "1"){"数据库"}elseif($styleChoice -eq "2"){"Database"}elseif($styleChoice -eq "3"){"数据库？"}else{"DB"})
Show-Option -Style $styleChoice -Key "1" -Text "MySQL"
Show-Option -Style $styleChoice -Key "2" -Text "PostgreSQL"
Show-Option -Style $styleChoice -Key "3" -Text $(if($styleChoice -eq "1"){"其他"}elseif($styleChoice -eq "2"){"Other"}else{"Other"})
$p = switch ($styleChoice) { "2" {">"} "4" {"Select:"} default {"选择 (1-3)"} }
do { $db = Read-Host $p } while ($db -notin @("1","2","3"))
switch ($db) {
    "1" { $database = "MySQL" }
    "2" { $database = "PostgreSQL" }
    "3" { 
        $dbPrompt = switch ($styleChoice) { "2" {"DB:"} "4" {"DB:"} default {"数据库类型"} }
        $database = Read-Host $dbPrompt
        while ([string]::IsNullOrWhiteSpace($database)) { $database = Read-Host $(if($styleChoice -eq "3"){"不能为空："}else{"Required:"}) }
    }
}

# Vue版本
$vueVer = "N/A"
if ($view -eq "Vue") {
    Write-Host ""
    Write-Host $(if($styleChoice -eq "1"){"Vue 版本"}elseif($styleChoice -eq "2"){"Vue Ver"}elseif($styleChoice -eq "3"){"Vue 版本？"}else{"Vue"}) -ForegroundColor Blue
    Show-Option -Style $styleChoice -Key "1" -Text "Vue 2"
    Show-Option -Style $styleChoice -Key "2" -Text "Vue 3" -Rec $true
    $p = switch ($styleChoice) { "2" {">"} "4" {"Select:"} default {"选择 (1-2)"} }
    do { $v = Read-Host $p } while ($v -notin @("1","2"))
    $vueVer = if ($v -eq "1") { "Vue2" } else { "Vue3" }
}

# 确认
Write-Host ""
Write-Host "=======================================================" -ForegroundColor Cyan
$confirmText = switch ($styleChoice) {
    "1" { "确认生成 $dirName ? (Y/N)" }
    "2" { "Execute? [Y/n]" }
    "3" { "生成到当前文件夹？(Y/N)" }
    "4" { "Go? (Y/N)" }
}
$confirm = Read-Host $confirmText
if ($confirm -ne 'Y' -and $confirm -ne 'y') { exit }

# ==========================================
# 5. 生成文件
# ==========================================

Write-Host ""
Write-Host "$(if($styleChoice -eq "3"){"开始生成... 🚀"}elseif($styleChoice -eq "2"){"[BUILD]..."}else{"开始生成..."})" -ForegroundColor Cyan

$uiDir = Join-Path $projectDir "ui"
$webDir = Join-Path $projectDir "web"
New-Item -ItemType Directory -Path $uiDir -Force | Out-Null
New-Item -ItemType Directory -Path $webDir -Force | Out-Null

Show-Success -Style $styleChoice -Message $(if($styleChoice -eq "3"){"目录创建成功！"}else{"Directories created"})

# 读取并替换
$webContent = Get-Content -Path $globalWebTemplate -Raw -Encoding UTF8
$uiContent = Get-Content -Path $globalUiTemplate -Raw -Encoding UTF8

$vars = @{
    '{{MODE}}' = $mode
    '{{BACKEND_PATH}}' = $backendPath
    '{{SPRING_VERSION}}' = $spring
    '{{VIEW_TECH}}' = $view
    '{{DATABASE}}' = $database
    '{{VUE_VERSION}}' = $vueVer
    '{{DATE}}' = (Get-Date -Format "yyyy-MM-dd")
    '{{TIMESTAMP}}' = (Get-Date -Format "yyyyMMdd_HHmmss")
    '{{CURRENT_PATH}}' = $currentPath
    '{{DIR_NAME}}' = $dirName
}

function Replace-Vars($content, $vars) {
    $result = $content
    $vars.GetEnumerator() | ForEach-Object { $result = $result.Replace($_.Key, $_.Value) }
    return $result
}

$generatedWeb = Replace-Vars -content $webContent -vars $vars
$generatedUi = Replace-Vars -content $uiContent -vars $vars

# 生成 Soul.md（使用字符串拼接避免 Here-String 问题）
$dateStr = $vars['{{DATE}}']
$modeStr = $vars['{{MODE}}']
$springStr = $vars['{{SPRING_VERSION}}']
$dbStr = $vars['{{DATABASE}}']
$viewStr = $vars['{{VIEW_TECH}}']
$vueStr = $vars['{{VUE_VERSION}}']

$soulLines = switch ($styleChoice) {
    "1" {
        @(
            "# $dirName Configuration",
            "",
            "## Metadata",
            "- **Date**: $dateStr",
            "- **Mode**: $modeStr",
            "- **Stack**: $springStr + $dbStr + $viewStr",
            "",
            "## Paths",
            "- **Global Template**: $globalDir",
            "- **Local Path**: $currentPath\$dirName"
        )
    }
    "2" {
        @(
            "# $dirName CONFIG",
            "",
            "DATE=$dateStr",
            "MODE=$modeStr",
            "STACK=$springStr+$dbStr+$viewStr",
            "GLOBAL=$globalDir",
            "LOCAL=$currentPath\$dirName"
        )
    }
    "3" {
        @(
            "# $dirName 配置 📋",
            "",
            "**生成时间**: $dateStr",
            "**模式**: $modeStr",
            "**技术栈**: $springStr + $dbStr + $viewStr $(if($vueStr -ne 'N/A'){"($vueStr)"})",
            "",
            "**全局模板**: $globalDir",
            "**本地路径**: $currentPath\$dirName"
        )
    }
    "4" {
        @(
            "$dirName",
            "---",
            "$dateStr | $modeStr | $springStr+$dbStr",
            "Global: $globalDir",
            "Local: $currentPath\$dirName"
        )
    }
}

$soulContent = $soulLines -join "`r`n"

# 写入文件
$generatedWeb | Out-File -FilePath (Join-Path $webDir "web.md") -Encoding UTF8
$generatedUi | Out-File -FilePath (Join-Path $uiDir "ui.md") -Encoding UTF8
$soulContent | Out-File -FilePath (Join-Path $projectDir "Soul.md") -Encoding UTF8

Show-Success -Style $styleChoice -Message $(if($styleChoice -eq "3"){"完成！"}else{"Complete"})

Write-Host ""
switch ($styleChoice) {
    "1" {
        Write-Host "生成位置：$projectDir" -ForegroundColor Green
        Write-Host "结构：$dirName/ui/, $dirName/web/, $dirName/Soul.md" -ForegroundColor Gray
    }
    "2" {
        Write-Host "[DONE] $projectDir" -ForegroundColor Green
        Write-Host "TREE: ui/ web/ Soul.md" -ForegroundColor Gray
    }
    "3" {
        Write-Host "搞定！位置：$projectDir" -ForegroundColor Green
        Write-Host "包含：ui/ui.md, web/web.md, Soul.md" -ForegroundColor Gray
    }
    "4" {
        Write-Host "Done: $projectDir" -ForegroundColor Green
    }
}
Write-Host ""
